### ISSUE TITLE
 Bypass of verification process in django admin page of openedx 

### ISSUE THREAD

**Issue by sivashankerN** [openedx-vlead/college-cloud#17] opened 2017-02-15 09:15 UTC
Disable sending verification emails to registered users in OpenedX.

Once the use is registered, users should be activated automatically, and should be able to login without verification of email id.

**Comment by ashay-maheshwari** [comment] 2017-02-16 10:53
Duplicate of #21 , resolved by using Database Trigger. Visit the issue for more details. 
Closing this issue.

**Closed by ashay-maheshwari** 2017-02-16 10:53 UTC
