### ISSUE TITLE
Hide a course in Open edX College Cloud Edition

### ISSUE THREAD

**Issue by ashay-maheshwari** [openedx-vlead/college-cloud#34] opened 2017-03-07 04:55 UTC
**Issue**
Considering observations and feedback from Workshop in Matrusri College of Engineering, it was seen that students were randomly wandering around all the courses in College Cloud Edition. Since we are not running all courses in College Cloud Edition (tough they are available and visible, simulation and images don't work and appear ). This just disturbed students jumping around completely killing the focus from workshop.

**Solution** 

Hiding the courses from catalog, which we don't want to open for workshop will remove this issue. Workshop Coordinator/Admin will have to un-hide courses, following the guidelines to make this happen.
Courses to be considered for Workshop will only be visible in Course Catalog. 

**Steps to hide a course**

1. - Login into Studio
2. - Select a lab
3. - From Settings-> Advanced Settings, Look for option "Invitation Only". 
4. - Set "Invitation only" to true.
5. - Save changes in studio.
6. - Lab will not appear in Course Lab now.

**Steps to un-hide a Lab**

1. - Login into Studio
2. - Select a Lab
3. - From Settings-> Advanced Settings, Look for option "Invitation Only". 
4. - Set "Invitation only" to false.
5. - Save changes in studio.
6. - Lab will appear in Lab Catalog now.

**Process** 
1. Identify the Lab to be used in workshops
2. Login to Studio 
3. Click the selected Lab
4. Change "Invitation Only" to false
5. Repeat the steps for all labs considered for workshop
6. Selected Labs will appear in the Lab catalog and rest of them will not.

**Comment by ashay-maheshwari** [comment] 2017-03-07 06:52
**Plan**

All Labs must be hidden by default. This must be given in college Cloud. 
Workshop coordinator will follow the instructions to unhide the labs considered for  workshop

**Comment by kraghupathi** [comment] 2017-03-07 10:22
**Follow the below steps for hiding a course in OpenedX studio.**

1.  Login into studio
2.  Select a Lab
3.  From  Settings --> Shedule & Details ---> Look for Course Shedule start date ---> change date greater than current date. 
**For example** : 10-05-2017 > 07-04-2017
4. From Settings-> Advanced Settings, Look for option "Course Advertised Start Date
" to "Anytime".
5. Set "Invitation only" to true.
6. Save changes in studio.
7. Lab will not appear in Course Lab now.

**Comment by sivashankerN** [comment] 2017-03-20 06:17
Duplicate of #36

**Closed by sivashankerN** 2017-03-20 06:17 UTC
